FROM python:3.14-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    gcc \
    g++ \
    python3-dev \
 && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/parser

WORKDIR /parser

ENV UV_LINK_MODE=copy
ENV VIRTUAL_ENV=/parser/.venv
ENV PATH="/parser/.venv/bin:$PATH"

COPY pyproject.toml .
RUN uv sync --no-dev
COPY . .

CMD ["uvicorn", "parser_app.main:app", "--host", "0.0.0.0", "--port", "8001"]
